version: "3.6"

volumes:
  db_data:

services:
  db:
    image: postgres:14-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"


  back:
    build:
      context: .
#      args:
#        DOCKER_BUILDKIT: 1
    volumes:
      - ./bin:/var/lib/jetty/webapps
       #/opt/java/openjdk/lib/security"
      - ./temp:/home
      #- /etc/ssl/certs/java/cacerts:/etc/ssl/certs/java/cacerts
#      - ./config/custom.ini:/var/lib/jetty/start.d/custom.ini
#      - ./data/fls:/opt/fls
#      - ../../ec-server/reports/:/opt/fls/sed_prod/0/reports/
#    command:
#      - "openssl s_client -showcerts -connect rusgardserver:443 </dev/null 2>/dev/null|openssl x509 -outform PEM >mycertfile.pem"
#      - "$JAVA_HOME/bin/keytool -import -alias Alias -keystore $JAVA_HOME/lib/security/cacerts -file mycertfile.pem -storepass 9244Lassk -noprompt"
    environment:
        CMS_JAVA_OPTS: '... -Djavax.net.ssl.trustStore=/srv/custom_keystore/cacerts -Djavax.net.ssl.trustStorePassword=changeit'
        CMS_HEAP_SIZE: '8g'
    ports:
      - "127.0.0.1:8080:8080"


#  prod-redis:
#    image: redis:6.2.8-alpine
#    volumes:
#      - ./data/redis:/data:rw
#    ports:
#      # - "127.0.0.1:24005:6379"
#      - "24005:6379"
#
#  front:
#    build:
#      context: ec-ui
#    volumes:
#      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "127.0.0.1:24009:80"
#
#  db-admin:
#    image: dpage/pgadmin4:6.21
#    ports:
#      - "127.0.0.1:24010:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: test@test.te
#      PGADMIN_DEFAULT_PASSWORD: testTEST11!!

